FROM nginx
sudo apt-get install php5-common php5-cli php5-fpm
COPY website/website/* /var/www
COPY website/website/* /usr/share/nginx/html
sed -i 's/index  index.html index.htm/index index.php index.html index.htm/' /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD /usr/sbin/nginx -g "daemon off;"
